#!/bin/bash
set -e

set -a
source .env
set +a

docker compose -f docker-compose.yml up -d postgres

until docker compose -f docker-compose.yml exec -T postgres \
    pg_isready -U dashboard -d dashboard; do
    sleep 1
done

cargo sqlx prepare

docker compose -f docker-compose.yml build
docker compose -f docker-compose.yml up -d
